trigger:
  branches:
    include:
      - develop

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '10.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.slnx'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.slnx'
    arguments: '--configuration $(buildConfiguration) --no-restore'

# - task: DotNetCoreCLI@2
#   displayName: 'Test'
#   inputs:
#     command: 'test'
#     projects: '**/*Tests/*.csproj'
#     arguments: '--configuration $(buildConfiguration) --no-build'

- task: DotNetCoreCLI@2
  displayName: 'Publish API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/Ticketing.Api.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- script: |
    npm install -g @railway/cli
    railway link --project $(RAILWAY_PROJECT_ID) --environment production
    railway up --ci --service ticketing-api
  displayName: 'Deploy to Railway'
  env:
    RAILWAY_TOKEN: $(RAILWAY_TOKEN)
    RAILWAY_PROJECT_ID: $(RAILWAY_PROJECT_ID)
