//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ticketing.Api.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La catégorie doit avoir un nom.
        /// </summary>
        internal static string CagetoryMustHaveNameMessage {
            get {
                return ResourceManager.GetString("CagetoryMustHaveNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il existe une categorie avec le même nom..
        /// </summary>
        internal static string CategoryExistsMessage {
            get {
                return ResourceManager.GetString("CategoryExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiant de la catégorie manquant.
        /// </summary>
        internal static string CategoryIdRequiredMessage {
            get {
                return ResourceManager.GetString("CategoryIdRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ou mot de passe incorrect.
        /// </summary>
        internal static string InvalidCredentialsMessage {
            get {
                return ResourceManager.GetString("InvalidCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message manquant.
        /// </summary>
        internal static string MessageRequiredMessage {
            get {
                return ResourceManager.GetString("MessageRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La page doit etre entre 1 et 100.
        /// </summary>
        internal static string PageBetweenOneAndHundred {
            get {
                return ResourceManager.GetString("PageBetweenOneAndHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La page doit etre supérieur à 1.
        /// </summary>
        internal static string PageMustGreaterThanOne {
            get {
                return ResourceManager.GetString("PageMustGreaterThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur doit avoir un mot de passe.
        /// </summary>
        internal static string PasswordRequiredMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe trop court.
        /// </summary>
        internal static string PasswordTooShortMessage {
            get {
                return ResourceManager.GetString("PasswordTooShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La catégorie n&apos;existe pas le ticket doit avoir une catégorie.
        /// </summary>
        internal static string TicketCategoryNotFoundMessage {
            get {
                return ResourceManager.GetString("TicketCategoryNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le ticket doit avoir un Id.
        /// </summary>
        internal static string TicketIdRequiredMessage {
            get {
                return ResourceManager.GetString("TicketIdRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le ticket doit avoir un objet.
        /// </summary>
        internal static string TicketMustHaveTitleMessage {
            get {
                return ResourceManager.GetString("TicketMustHaveTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket introuvable.
        /// </summary>
        internal static string TicketNotFoundMessage {
            get {
                return ResourceManager.GetString("TicketNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un utilisateur avec ce mail existe déja.
        /// </summary>
        internal static string UserExistsMessage {
            get {
                return ResourceManager.GetString("UserExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur doit avoir un identifiant.
        /// </summary>
        internal static string UserIdRequiredMessage {
            get {
                return ResourceManager.GetString("UserIdRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur doit avoir un email.
        /// </summary>
        internal static string UserMustHaveEmailMessage {
            get {
                return ResourceManager.GetString("UserMustHaveEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur doit avoir un nom.
        /// </summary>
        internal static string UserMustHaveFullNameMessage {
            get {
                return ResourceManager.GetString("UserMustHaveFullNameMessage", resourceCulture);
            }
        }
    }
}
